// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"PaiPai/apps/eino_chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 调用智能体
				Method:  http.MethodPost,
				Path:    "/agent/invoke",
				Handler: AgentInvokeHandler(serverCtx),
			},
			{
				// 聊天补全
				Method:  http.MethodPost,
				Path:    "/chat/completions",
				Handler: ChatCompletionHandler(serverCtx),
			},
			{
				// 聊天流式输出
				Method:  http.MethodPost,
				Path:    "/chat/stream",
				Handler: ChatStreamHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
