// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: eino.proto

package einoclient

import (
	"context"

	"PaiPai/apps/eino_chat/rpc/eino"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResp                 = eino.BaseResp
	ChatCompletionReq        = eino.ChatCompletionReq
	ChatCompletionResp       = eino.ChatCompletionResp
	ChatCompletionStreamReq  = eino.ChatCompletionStreamReq
	ChatCompletionStreamResp = eino.ChatCompletionStreamResp
	InvokeAgentReq           = eino.InvokeAgentReq
	InvokeAgentResp          = eino.InvokeAgentResp
	Message                  = eino.Message

	Eino interface {
		// 单次对话
		ChatCompletion(ctx context.Context, in *ChatCompletionReq, opts ...grpc.CallOption) (*ChatCompletionResp, error)
		// 流式对话
		ChatCompletionStream(ctx context.Context, in *ChatCompletionStreamReq, opts ...grpc.CallOption) (eino.Eino_ChatCompletionStreamClient, error)
		// 调用已注册的 Agent
		InvokeAgent(ctx context.Context, in *InvokeAgentReq, opts ...grpc.CallOption) (*InvokeAgentResp, error)
	}

	defaultEino struct {
		cli zrpc.Client
	}
)

func NewEino(cli zrpc.Client) Eino {
	return &defaultEino{
		cli: cli,
	}
}

// 单次对话
func (m *defaultEino) ChatCompletion(ctx context.Context, in *ChatCompletionReq, opts ...grpc.CallOption) (*ChatCompletionResp, error) {
	client := eino.NewEinoClient(m.cli.Conn())
	return client.ChatCompletion(ctx, in, opts...)
}

// 流式对话
func (m *defaultEino) ChatCompletionStream(ctx context.Context, in *ChatCompletionStreamReq, opts ...grpc.CallOption) (eino.Eino_ChatCompletionStreamClient, error) {
	client := eino.NewEinoClient(m.cli.Conn())
	return client.ChatCompletionStream(ctx, in, opts...)
}

// 调用已注册的 Agent
func (m *defaultEino) InvokeAgent(ctx context.Context, in *InvokeAgentReq, opts ...grpc.CallOption) (*InvokeAgentResp, error) {
	client := eino.NewEinoClient(m.cli.Conn())
	return client.InvokeAgent(ctx, in, opts...)
}
