// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: apps/eino_chat/rpc/eino.proto

package eino

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Eino_ChatCompletion_FullMethodName       = "/eino.Eino/ChatCompletion"
	Eino_ChatCompletionStream_FullMethodName = "/eino.Eino/ChatCompletionStream"
	Eino_InvokeAgent_FullMethodName          = "/eino.Eino/InvokeAgent"
)

// EinoClient is the client API for Eino service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------- 服务定义 ----------------
type EinoClient interface {
	// 单次对话
	ChatCompletion(ctx context.Context, in *ChatCompletionReq, opts ...grpc.CallOption) (*ChatCompletionResp, error)
	// 流式对话
	ChatCompletionStream(ctx context.Context, in *ChatCompletionStreamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionStreamResp], error)
	// 调用已注册的 Agent
	InvokeAgent(ctx context.Context, in *InvokeAgentReq, opts ...grpc.CallOption) (*InvokeAgentResp, error)
}

type einoClient struct {
	cc grpc.ClientConnInterface
}

func NewEinoClient(cc grpc.ClientConnInterface) EinoClient {
	return &einoClient{cc}
}

func (c *einoClient) ChatCompletion(ctx context.Context, in *ChatCompletionReq, opts ...grpc.CallOption) (*ChatCompletionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResp)
	err := c.cc.Invoke(ctx, Eino_ChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *einoClient) ChatCompletionStream(ctx context.Context, in *ChatCompletionStreamReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionStreamResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Eino_ServiceDesc.Streams[0], Eino_ChatCompletionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionStreamReq, ChatCompletionStreamResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Eino_ChatCompletionStreamClient = grpc.ServerStreamingClient[ChatCompletionStreamResp]

func (c *einoClient) InvokeAgent(ctx context.Context, in *InvokeAgentReq, opts ...grpc.CallOption) (*InvokeAgentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeAgentResp)
	err := c.cc.Invoke(ctx, Eino_InvokeAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EinoServer is the server API for Eino service.
// All implementations must embed UnimplementedEinoServer
// for forward compatibility.
//
// ---------------- 服务定义 ----------------
type EinoServer interface {
	// 单次对话
	ChatCompletion(context.Context, *ChatCompletionReq) (*ChatCompletionResp, error)
	// 流式对话
	ChatCompletionStream(*ChatCompletionStreamReq, grpc.ServerStreamingServer[ChatCompletionStreamResp]) error
	// 调用已注册的 Agent
	InvokeAgent(context.Context, *InvokeAgentReq) (*InvokeAgentResp, error)
	mustEmbedUnimplementedEinoServer()
}

// UnimplementedEinoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEinoServer struct{}

func (UnimplementedEinoServer) ChatCompletion(context.Context, *ChatCompletionReq) (*ChatCompletionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedEinoServer) ChatCompletionStream(*ChatCompletionStreamReq, grpc.ServerStreamingServer[ChatCompletionStreamResp]) error {
	return status.Errorf(codes.Unimplemented, "method ChatCompletionStream not implemented")
}
func (UnimplementedEinoServer) InvokeAgent(context.Context, *InvokeAgentReq) (*InvokeAgentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeAgent not implemented")
}
func (UnimplementedEinoServer) mustEmbedUnimplementedEinoServer() {}
func (UnimplementedEinoServer) testEmbeddedByValue()              {}

// UnsafeEinoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EinoServer will
// result in compilation errors.
type UnsafeEinoServer interface {
	mustEmbedUnimplementedEinoServer()
}

func RegisterEinoServer(s grpc.ServiceRegistrar, srv EinoServer) {
	// If the following call pancis, it indicates UnimplementedEinoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Eino_ServiceDesc, srv)
}

func _Eino_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EinoServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Eino_ChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EinoServer).ChatCompletion(ctx, req.(*ChatCompletionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eino_ChatCompletionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EinoServer).ChatCompletionStream(m, &grpc.GenericServerStream[ChatCompletionStreamReq, ChatCompletionStreamResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Eino_ChatCompletionStreamServer = grpc.ServerStreamingServer[ChatCompletionStreamResp]

func _Eino_InvokeAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeAgentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EinoServer).InvokeAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Eino_InvokeAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EinoServer).InvokeAgent(ctx, req.(*InvokeAgentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Eino_ServiceDesc is the grpc.ServiceDesc for Eino service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Eino_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eino.Eino",
	HandlerType: (*EinoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatCompletion",
			Handler:    _Eino_ChatCompletion_Handler,
		},
		{
			MethodName: "InvokeAgent",
			Handler:    _Eino_InvokeAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatCompletionStream",
			Handler:       _Eino_ChatCompletionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "apps/eino_chat/rpc/eino.proto",
}
