// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: apps/eino_chat/rpc/eino.proto

package eino

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------- 基础模型 ----------------
// 统一响应
type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_apps_eino_chat_rpc_eino_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 单条消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_apps_eino_chat_rpc_eino_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ---------------- 单次对话 ----------------
type ChatCompletionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionReq) Reset() {
	*x = ChatCompletionReq{}
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionReq) ProtoMessage() {}

func (x *ChatCompletionReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionReq.ProtoReflect.Descriptor instead.
func (*ChatCompletionReq) Descriptor() ([]byte, []int) {
	return file_apps_eino_chat_rpc_eino_proto_rawDescGZIP(), []int{2}
}

func (x *ChatCompletionReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionReq) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChatCompletionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Reply         string                 `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionResp) Reset() {
	*x = ChatCompletionResp{}
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResp) ProtoMessage() {}

func (x *ChatCompletionResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResp.ProtoReflect.Descriptor instead.
func (*ChatCompletionResp) Descriptor() ([]byte, []int) {
	return file_apps_eino_chat_rpc_eino_proto_rawDescGZIP(), []int{3}
}

func (x *ChatCompletionResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ChatCompletionResp) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

// ---------------- 流式对话 ----------------
type ChatCompletionStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionStreamReq) Reset() {
	*x = ChatCompletionStreamReq{}
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionStreamReq) ProtoMessage() {}

func (x *ChatCompletionStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionStreamReq.ProtoReflect.Descriptor instead.
func (*ChatCompletionStreamReq) Descriptor() ([]byte, []int) {
	return file_apps_eino_chat_rpc_eino_proto_rawDescGZIP(), []int{4}
}

func (x *ChatCompletionStreamReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionStreamReq) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 每帧返回
type ChatCompletionStreamResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Chunk         string                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"` // 增量内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionStreamResp) Reset() {
	*x = ChatCompletionStreamResp{}
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionStreamResp) ProtoMessage() {}

func (x *ChatCompletionStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionStreamResp.ProtoReflect.Descriptor instead.
func (*ChatCompletionStreamResp) Descriptor() ([]byte, []int) {
	return file_apps_eino_chat_rpc_eino_proto_rawDescGZIP(), []int{5}
}

func (x *ChatCompletionStreamResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ChatCompletionStreamResp) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

// ---------------- Agent 调用 ----------------
type InvokeAgentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"` // 任意 JSON，由 Agent 定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeAgentReq) Reset() {
	*x = InvokeAgentReq{}
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeAgentReq) ProtoMessage() {}

func (x *InvokeAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeAgentReq.ProtoReflect.Descriptor instead.
func (*InvokeAgentReq) Descriptor() ([]byte, []int) {
	return file_apps_eino_chat_rpc_eino_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeAgentReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *InvokeAgentReq) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type InvokeAgentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResp              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // Agent 返回的 JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeAgentResp) Reset() {
	*x = InvokeAgentResp{}
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeAgentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeAgentResp) ProtoMessage() {}

func (x *InvokeAgentResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_eino_chat_rpc_eino_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeAgentResp.ProtoReflect.Descriptor instead.
func (*InvokeAgentResp) Descriptor() ([]byte, []int) {
	return file_apps_eino_chat_rpc_eino_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeAgentResp) GetBase() *BaseResp {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *InvokeAgentResp) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_apps_eino_chat_rpc_eino_proto protoreflect.FileDescriptor

const file_apps_eino_chat_rpc_eino_proto_rawDesc = "" +
	"\n" +
	"\x1dapps/eino_chat/rpc/eino.proto\x12\x04eino\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"T\n" +
	"\x11ChatCompletionReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12)\n" +
	"\bmessages\x18\x02 \x03(\v2\r.eino.MessageR\bmessages\"N\n" +
	"\x12ChatCompletionResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.eino.BaseRespR\x04base\x12\x14\n" +
	"\x05reply\x18\x02 \x01(\tR\x05reply\"Z\n" +
	"\x17ChatCompletionStreamReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12)\n" +
	"\bmessages\x18\x02 \x03(\v2\r.eino.MessageR\bmessages\"T\n" +
	"\x18ChatCompletionStreamResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.eino.BaseRespR\x04base\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\tR\x05chunk\"A\n" +
	"\x0eInvokeAgentReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\"M\n" +
	"\x0fInvokeAgentResp\x12\"\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.eino.BaseRespR\x04base\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output2\xe0\x01\n" +
	"\x04Eino\x12C\n" +
	"\x0eChatCompletion\x12\x17.eino.ChatCompletionReq\x1a\x18.eino.ChatCompletionResp\x12W\n" +
	"\x14ChatCompletionStream\x12\x1d.eino.ChatCompletionStreamReq\x1a\x1e.eino.ChatCompletionStreamResp0\x01\x12:\n" +
	"\vInvokeAgent\x12\x14.eino.InvokeAgentReq\x1a\x15.eino.InvokeAgentRespB\bZ\x06./einob\x06proto3"

var (
	file_apps_eino_chat_rpc_eino_proto_rawDescOnce sync.Once
	file_apps_eino_chat_rpc_eino_proto_rawDescData []byte
)

func file_apps_eino_chat_rpc_eino_proto_rawDescGZIP() []byte {
	file_apps_eino_chat_rpc_eino_proto_rawDescOnce.Do(func() {
		file_apps_eino_chat_rpc_eino_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_eino_chat_rpc_eino_proto_rawDesc), len(file_apps_eino_chat_rpc_eino_proto_rawDesc)))
	})
	return file_apps_eino_chat_rpc_eino_proto_rawDescData
}

var file_apps_eino_chat_rpc_eino_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_apps_eino_chat_rpc_eino_proto_goTypes = []any{
	(*BaseResp)(nil),                 // 0: eino.BaseResp
	(*Message)(nil),                  // 1: eino.Message
	(*ChatCompletionReq)(nil),        // 2: eino.ChatCompletionReq
	(*ChatCompletionResp)(nil),       // 3: eino.ChatCompletionResp
	(*ChatCompletionStreamReq)(nil),  // 4: eino.ChatCompletionStreamReq
	(*ChatCompletionStreamResp)(nil), // 5: eino.ChatCompletionStreamResp
	(*InvokeAgentReq)(nil),           // 6: eino.InvokeAgentReq
	(*InvokeAgentResp)(nil),          // 7: eino.InvokeAgentResp
}
var file_apps_eino_chat_rpc_eino_proto_depIdxs = []int32{
	1, // 0: eino.ChatCompletionReq.messages:type_name -> eino.Message
	0, // 1: eino.ChatCompletionResp.base:type_name -> eino.BaseResp
	1, // 2: eino.ChatCompletionStreamReq.messages:type_name -> eino.Message
	0, // 3: eino.ChatCompletionStreamResp.base:type_name -> eino.BaseResp
	0, // 4: eino.InvokeAgentResp.base:type_name -> eino.BaseResp
	2, // 5: eino.Eino.ChatCompletion:input_type -> eino.ChatCompletionReq
	4, // 6: eino.Eino.ChatCompletionStream:input_type -> eino.ChatCompletionStreamReq
	6, // 7: eino.Eino.InvokeAgent:input_type -> eino.InvokeAgentReq
	3, // 8: eino.Eino.ChatCompletion:output_type -> eino.ChatCompletionResp
	5, // 9: eino.Eino.ChatCompletionStream:output_type -> eino.ChatCompletionStreamResp
	7, // 10: eino.Eino.InvokeAgent:output_type -> eino.InvokeAgentResp
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_apps_eino_chat_rpc_eino_proto_init() }
func file_apps_eino_chat_rpc_eino_proto_init() {
	if File_apps_eino_chat_rpc_eino_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_eino_chat_rpc_eino_proto_rawDesc), len(file_apps_eino_chat_rpc_eino_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_eino_chat_rpc_eino_proto_goTypes,
		DependencyIndexes: file_apps_eino_chat_rpc_eino_proto_depIdxs,
		MessageInfos:      file_apps_eino_chat_rpc_eino_proto_msgTypes,
	}.Build()
	File_apps_eino_chat_rpc_eino_proto = out.File
	file_apps_eino_chat_rpc_eino_proto_goTypes = nil
	file_apps_eino_chat_rpc_eino_proto_depIdxs = nil
}
