FROM alpine:3.18

# 添加时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.15/main\nhttps://mirrors.aliyun.com/alpine/v3.15/community" > /etc/apk/repositories && \
    apk update &&\
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone
ENV TZ=Asia/Shanghai

ARG SERVER_NAME=task
ARG SERVER_TYPE=mq

ENV RUN_BIN=bin/${SERVER_NAME}-${SERVER_TYPE}
ENV RUN_CONF=/${SERVER_NAME}/conf/${SERVER_NAME}.yaml

# 将宿主机中的内容复制到容器中
# 命令 左边是宿主机的目录，右边是容器目录
RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf

# 复制编译后的二进制文件
COPY ./bin/$SERVER_NAME-$SERVER_TYPE /$SERVER_NAME/bin/

# 复制配置文件
COPY ./apps/$SERVER_NAME/$SERVER_TYPE/etc/dev/$SERVER_NAME.yaml /$SERVER_NAME/conf/

# 为二进制提供执行权限
RUN chmod +x /$SERVER_NAME/bin/$SERVER_NAME-$SERVER_TYPE

# 指定容器会默认进入那个目录
WORKDIR /$SERVER_NAME

# 使用sh -c来支持环境变量解析并保持JSON格式
ENTRYPOINT ["sh", "-c", "$RUN_BIN -f $RUN_CONF"]
