FROM alpine:3.14

RUN apk add --no-cache wget && \
    wget -q https://github.com/etcd-io/etcd/releases/download/v3.6.0/etcd-v3.6.0-linux-amd64.tar.gz && \
    tar -xzf etcd-v3.6.0-linux-amd64.tar.gz && \
    cp etcd-v3.6.0-linux-amd64/etcd /usr/local/bin/ && \
    cp etcd-v3.6.0-linux-amd64/etcdctl /usr/local/bin/ && \
    chmod +x /usr/local/bin/etcd /usr/local/bin/etcdctl && \
    rm -rf etcd-v3.6.0-linux-amd64*

EXPOSE 2379 2380

ENTRYPOINT ["etcd"]