syntax = "proto3";

package user;

option go_package = "./user";

// 模型model
message UserEntity {
  string id = 1;     // 用户id
  string avatar = 2;   // 用户头像
  string nickname = 3;  // 昵称
  string phone = 4;  // 手机号码
  int32 status = 5;  // 锁定状态
  int32 sex = 6;
  string username = 7; // 用户名
  string email = 8;   // 邮箱
}

// req && resp
message Request {
  string ping = 1;
}

message Response {
  string pong = 1;
}

message LoginReq {
  string username = 1;
  string password = 2;
}

message LoginResp {
  string Id = 3;
  string Token = 1;
  int64 expire = 2;
}

message RegisterReq{
  string username = 1;
  string password = 2;
  string email = 3;
  string phone = 4;
  string nickname = 5;
  string avatar = 6;
  int32 sex = 7;
}

message RegisterResp{
  string Token = 1;
  int64 expire = 2;
}

message GetUserInfoReq{
  string id = 1;
}

message GetUserInfoResp{
  UserEntity user = 1;
}

message FindUserReq{
  string name = 1;
  string phone = 2;
  repeated string ids = 3;
}

message FindUserResp{
  repeated UserEntity user = 1;
}

service User{
  rpc Ping(Request) returns(Response);
  rpc Login(LoginReq) returns(LoginResp);
  rpc Register(RegisterReq) returns(RegisterResp);
  rpc GetUserInfo(GetUserInfoReq) returns(GetUserInfoResp);
  rpc FindUser(FindUserReq) returns(FindUserResp);
}
