// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AgentInvokeReq struct {
	AgentID string      `json:"agent_id"`
	Input   interface{} `json:"input"`
}

type AgentInvokeResp struct {
	BaseResp BaseResp    `json:"BaseResp"`
	Output   interface{} `json:"output"`
}

type BaseResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg,omitempty"`
}

type ChatCompletionReq struct {
	Model    string    `json:"model"`
	Messages []Message `json:"messages"`
}

type ChatCompletionResp struct {
	BaseResp BaseResp `json:"BaseResp"`
	Reply    string   `json:"reply"`
}

type ChatStreamReq struct {
	Model    string    `json:"model"`
	Messages []Message `json:"messages"`
}

type ChatStreamResp struct {
	BaseResp BaseResp `json:"BaseResp"`
	Chunk    string   `json:"chunk"`
}

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}
