// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: eino.proto

package server

import (
	"context"

	"PaiPai/apps/eino_chat/rpc/eino"
	"PaiPai/apps/eino_chat/rpc/internal/logic"
	"PaiPai/apps/eino_chat/rpc/internal/svc"
)

type EinoServer struct {
	svcCtx *svc.ServiceContext
	eino.UnimplementedEinoServer
}

func NewEinoServer(svcCtx *svc.ServiceContext) *EinoServer {
	return &EinoServer{
		svcCtx: svcCtx,
	}
}

// 单次对话
func (s *EinoServer) ChatCompletion(ctx context.Context, in *eino.ChatCompletionReq) (*eino.ChatCompletionResp, error) {
	l := logic.NewChatCompletionLogic(ctx, s.svcCtx)
	return l.ChatCompletion(in)
}

// 流式对话
func (s *EinoServer) ChatCompletionStream(in *eino.ChatCompletionStreamReq, stream eino.Eino_ChatCompletionStreamServer) error {
	l := logic.NewChatCompletionStreamLogic(stream.Context(), s.svcCtx)
	return l.ChatCompletionStream(in, stream)
}

// 调用已注册的 Agent
func (s *EinoServer) InvokeAgent(ctx context.Context, in *eino.InvokeAgentReq) (*eino.InvokeAgentResp, error) {
	l := logic.NewInvokeAgentLogic(ctx, s.svcCtx)
	return l.InvokeAgent(in)
}
